### PR TITLE
Rename eders to serde

### PR DESCRIPTION
**Pull request by torkleyy**
This change is [Reviewable](https://reviewable.io/reviews/rustgd/collision-rs/92)

### CODE REVIEW

**Comment by kvark** [comment]
Oh yeah, @Xaeroxe came up with this IIRC? Or was it you all along, @torkleyy ?

**Comment by Rhuagh** [comment]
@Xaeroxe complained about it and attempted a fix that didn't work I believe?

**Comment by torkleyy** [comment]
Not sure. Let me add a test before merging.

**Comment by torkleyy** [comment]
bors r=Rhuagh

**Comment by kvark** [comment]
@torkleyy try again plz

**Pull request merged**
