### PR TITLE
fix: Add Default implementation for DynamicBoundingVolumeTree

### PR DESCRIPTION
**Pull request by Rhuagh**
This change is [Reviewable](https://reviewable.io/reviews/rustgd/collision-rs/87)

### CODE REVIEW

**Comment by torkleyy** [comment]
The problem is that this causes users to add bounds directly to structs, which in general should be avoided.

**Comment by Rhuagh** [comment]
Why would it force that, the bounds are not in the actual struct?

**Comment by torkleyy** [comment]
It's required to derive `SystemData`.

**Comment by Rhuagh** [comment]
I guess that's true, I just find it incredibly frustrating when you create an instance of a  type, that works, and then when your want to use it you only get `no such function on this type `

**Comment by Rhuagh** [comment]
Updated in accordance with review.

**Comment by Rhuagh** [comment]
Bors r=torkleyy

**Pull request merged**
