### PR TITLE
Fix #122

### LINKED ISSUE #122: Warning declare by rust while compiling
warning: Found `feature = ...` in `target.'cfg(...)'.dependencies`. This key is not supported for selecting dependencies and will not work as expected. Use the [features] section instead: https://doc.rust-lang.org/cargo/reference/features.html

### PR DESCRIPTION
**Pull request by eadf**
This is how [the RSA crate](https://github.com/RustCrypto/RSA) solved the same problem.

https://github.com/rust-lang/api-guidelines/discussions/180

---
This change is [Reviewable](https://reviewable.io/reviews/rustgd/collision-rs/133)

### CODE REVIEW

**Comment by eadf** [comment]
#122

**Review by kvark — APPROVED** [review]
Pretty cool!

**Comment by eadf** [comment]
I'm sorry, but It seems like I forgot to make a `fmt` on these changes.

I read that we [can rename "serde_crate"](https://blog.turbo.fish/cargo-features/) back to "serde" with:
`extern crate serde_crate as serde;` in `lib.rs`. But it simply does not work with `#[cfg_attr(` 
(or possibly `#[macro_use]`).

Should I make a new PR with just the `fmt`?

**Comment by kvark** [comment]
sure, thanks!

**Pull request merged**
